using SensorsProject.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SensorsProject.Models.Sensors
{
    internal static class SensorManager
    {

        public static string[] sensorTypes = { "basic", "thermal" };
        public static string allSensorTypes = "";
        
        public static void PrintSensorTypes() {
            string types = "";
            foreach (string type in sensorTypes) {
                types += $"{type} ";
            }
            allSensorTypes = types;
            Console.WriteLine($"types: {types}");
        }
        public static SensorObj[] GetAllPossibleSensors()
        {
            SensorObj[] sensorArr = new SensorObj[sensorTypes.Length];
            for(int i=0;i< sensorTypes.Length; i++)
            {
                SensorObj sensor = GetSpecificSensor(sensorTypes[i]);
                sensorArr[i] = sensor;
            }
            return sensorArr;
        }

        public static SensorObj GetSpecificSensor(string sensorType)
        {
            if (sensorType == "basic") return new BasicSensor();
            if (sensorType == "thermal") return new ThermalSensor();

            Console.WriteLine($"[Warning] Unknown sensor type: {sensorType}, defaulting to BasicSensor");
            return new BasicSensor(); // Never return null

        }

        public static SensorObj genRandSensorSingle() {
            //Console.WriteLine("start genRandSensorSingle");
            Random rand = new Random();
            int randNum = rand.Next(sensorTypes.Length);
            //Console.WriteLine($"randNum: {randNum}");
            string sensorType = sensorTypes[randNum];
            //Console.WriteLine($"sensorType: {sensorType}");
            SensorObj newSensor = GetSpecificSensor(sensorType);
            //Console.WriteLine("end genRandSensorSingle");
            return newSensor;
        }
        public static SensorObj[] GenRandSensors(int num)
        {
            //Console.WriteLine("start GenRandSensors ");
            SensorObj[] sensorsList = new SensorObj[num];
            int counter = 0; 
            while (counter < num)
            {
                SensorObj newSensor = genRandSensorSingle();
                while(newSensor == null)
                {
                    newSensor = genRandSensorSingle();

                }
                sensorsList[counter] = newSensor;
                counter += 1;
            }
            //Console.WriteLine("nulls in sensor list generated by GenRandSensors ");
            //UtilMethods.nullCounter(sensorsList);
            return sensorsList;
        }
    }

}
